coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch: off

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: true
