#!/bin/bash

set -e

source ./common.inc.sh


build()
(
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"
    cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release "$BUILD_DIR_SOURCE" "$@"
    mingw32-make -j 4 iseql

)



switchToRelease
build

switchToCounters
build -DCOUNTERS=ON

switchToEBI
build -DEBI=ON
